### ISSUE TITLE
Gender chart color discrepancy

### ISSUE THREAD

**Issue by joerlop** [sauti-databank/front-end#37]
Gender chart bar color order does not follow Nivo convention as in all the other charts.

**Comment by kimberleejohnson** [comment]
Thanks for flagging, @joerlop! We fixed this by swapping the order of the keys in our Nivo gender chart, making sure female was listed first, because that is how we imported our data in the Nivo ResponsiveBar chart within the component (female, then male): https://github.com/sauti-databank/front-end/pull/50
